name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy to VPS
      - name: Deploy to Hostinger VPS
        uses: appleboy/ssh-action@v0.1.12
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          script: |
            cd ~/apps/buspay_server
            git pull origin main
            npm install --only=prod
            npm run build
            pm2 restart buspay_server
